language : python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install :
  - pip install -r requirements.txt

script :
  - ./hotstar-playlist-downloader/hotstar-playlist-downloader.py -s number -u http://www.hotstar.com/tv/mahabharat/435/seasons/season-1
  - coala --ci
